server:
  # Listening port of the server (default: 3000)
  port: 3000
oauth:
  # OAuth client id (required)
  client_id: ''
  # OAuth client secret (required)
  client_secret: ''
  # OAuth callback URL which should point to the path '/auth/login/callback' on this server and has
  # to be publicly reachable by the clients (required)
  callback_url: ''
session:
  cookie:
    # Secret for encrypting the session cookie (required)
    secret: ''
    # Max age of the session cookie in ms (default: 5 days)
    max_age: 432000000 # 5 days
    # The domain for which the session cookie belongs
    domain: ''
github:
  # Name of the Github org the user has to be a member of or empty to allow all users (default: empty)
  org: ''
logging:
  root_logger_name: ambassador-github-oauth
